version: '3.7'
services:
  opa:
    image: openpolicyagent/opa:0.18.0
    network_mode: host
    command:
      - "run"
      - "--server"
      - "--log-level=debug"
      - "--log-format=text"
      - "--addr=0.0.0.0:8181"
      - "/policies"
    volumes:
      - policies/:/policies
  minio:
    network-mode: host
    command:
      - "server"
      - "/data"
    environment:
      - MINIO_POLICY_OPA_URL=http://localhost:8181/v1/data/httpapi/authz/allow
      - MINIO_IDENTITY_OPENID_CLIENT_ID="minio-auth"
      - MINIO_IDENTITY_OPENID_CONFIG_URL=http://90.147.174.92:5556/dex/.well-known/openid-configuration
    volumes:
      - data:/data