site_name: MINIO with OPA and IAM
theme:
  name: material
  logo:
    icon: cloud_circle
  palette:
    primary: "Deep Blue"
    accent: "Light Blue"
nav:
  - Home: "README.md"
repo_name: "dciangot/minio-opa"
repo_url: "https://github.com/dciangot/minio-opa"

extra:
  social:
    - type: "github"
      link: "https://github.com/dciangot/minio-opa"
    - type: "twitter"
      link: "https://twitter.com/imdciangot"

markdown_extensions:
  - codehilite
